#!/usr/bin/env bash
# seal-secret.sh — turn an unencrypted Secret manifest into a
# committable SealedSecret using the cluster's bitnami-labs/sealed-
# secrets controller.
#
# Why this is in scripts/: one-shot bootstrap operation. A SealedSecret
# is generated once per credential and then lives in Git as the GitOps
# source of truth. Re-sealing happens only when you rotate a credential
# (rare). Specifically: this gets deleted from your fork the moment
# upstream sealed-secrets ships a Kustomize generator that integrates
# directly into the GitOps tree. Until then, sealing happens out-of-
# band and the resulting YAML is committed.
#
# See .claude/rules/no-scripts-as-design.md for the rule.
#
# Companion files:
#   infrastructure/controllers/pvc-plumber/sealed-kopia-password.yaml
#       — generated by this script. Holds the kopia repo password +
#         S3 admin keys the operator uses.
#   docs/secret-management.md
#       — sealed-secrets default rationale + ESO/1Password/Vault
#         alternatives.
#
# Backend choice — sealed-secrets vs ESO + external store:
#   The starter ships sealed-secrets as the simpler default — one
#   controller, one CRD, one `kubeseal` invocation, no external
#   service to run. To swap to ESO + 1Password / HashiCorp Vault /
#   AWS Secrets Manager / GCP Secret Manager / Azure Key Vault /
#   etc., see docs/secret-management.md (the recipe is small: change
#   the ClusterSecretStore provider stanza, point at your backend,
#   delete the SealedSecret manifest).
#
# Usage:
#   # Pipe a Secret manifest in:
#   cat my-secret.yaml | ./scripts/seal-secret.sh > sealed.yaml
#
#   # Or pass file paths:
#   ./scripts/seal-secret.sh --in my-secret.yaml --out sealed.yaml
#
#   # Generate the kopia password SealedSecret in-place:
#   ./scripts/seal-secret.sh --kopia-password
#
#   ./scripts/seal-secret.sh --help

set -euo pipefail

SEALED_SECRETS_NAMESPACE="${SEALED_SECRETS_NAMESPACE:-sealed-secrets}"
SEALED_SECRETS_CONTROLLER="${SEALED_SECRETS_CONTROLLER:-sealed-secrets}"

usage() {
  sed -n '2,40p' "$0" | sed 's/^# *//'
}

# ─────────────────────────────────────────────────────────────────────
# Pre-flight: tools + cluster reachability
# ─────────────────────────────────────────────────────────────────────
preflight() {
  if ! command -v kubeseal > /dev/null 2>&1; then
    echo "ERROR: kubeseal is not installed." >&2
    echo "  Install: https://github.com/bitnami-labs/sealed-secrets/releases" >&2
    exit 1
  fi
  if ! command -v kubectl > /dev/null 2>&1; then
    echo "ERROR: kubectl is not installed." >&2
    exit 1
  fi
  if ! kubectl get -n "$SEALED_SECRETS_NAMESPACE" deployment "$SEALED_SECRETS_CONTROLLER" > /dev/null 2>&1; then
    echo "ERROR: sealed-secrets controller not found." >&2
    echo "  Looked for: deployment/$SEALED_SECRETS_CONTROLLER in namespace $SEALED_SECRETS_NAMESPACE" >&2
    echo "  Override via SEALED_SECRETS_NAMESPACE / SEALED_SECRETS_CONTROLLER env vars." >&2
    echo "  Wave 0 of the starter installs sealed-secrets — check ArgoCD: kubectl get app sealed-secrets -n argocd" >&2
    exit 1
  fi
}

# ─────────────────────────────────────────────────────────────────────
# Sanity-check a manifest only contains a Secret. Refuse anything else
# (avoid accidentally sealing a ConfigMap or a multi-doc YAML where the
# Secret is mixed with other resources — kubeseal happily processes
# whatever you give it; this script is the human-friendly gate).
# ─────────────────────────────────────────────────────────────────────
validate_secret_only() {
  local file="$1"
  if ! grep -qE '^kind:[[:space:]]+Secret[[:space:]]*$' "$file"; then
    echo "ERROR: input does not contain 'kind: Secret'." >&2
    echo "  This script seals Secret manifests only — not ConfigMaps," >&2
    echo "  multi-doc YAML, or arbitrary resources." >&2
    exit 1
  fi
  local kinds
  kinds=$(grep -cE '^kind:[[:space:]]+[A-Za-z]+' "$file" || true)
  if [ "$kinds" -gt 1 ]; then
    echo "ERROR: input has multiple 'kind:' declarations." >&2
    echo "  Split into separate files first; this script seals one Secret." >&2
    exit 1
  fi
}

# ─────────────────────────────────────────────────────────────────────
# Run kubeseal against the cluster. Output the SealedSecret YAML.
# ─────────────────────────────────────────────────────────────────────
seal() {
  local in="$1"
  local out="$2"
  kubeseal \
    --controller-namespace "$SEALED_SECRETS_NAMESPACE" \
    --controller-name "$SEALED_SECRETS_CONTROLLER" \
    --format yaml \
    < "$in" \
    > "$out"
}

# ─────────────────────────────────────────────────────────────────────
# Convenience: generate the kopia-password SealedSecret in-place,
# overwriting the placeholder file. The generated SealedSecret carries
# the three keys the pvc-plumber operator hardcodes: kopia_password,
# k8s-admin-access-key, k8s-admin-secret-key.
# ─────────────────────────────────────────────────────────────────────
kopia_password_workflow() {
  local target="infrastructure/controllers/pvc-plumber/sealed-kopia-password.yaml"
  if [ ! -f "$target" ]; then
    echo "ERROR: $target not found." >&2
    echo "  Run this script from the repo root." >&2
    exit 1
  fi

  # Generate a 32-byte random password (base64-encoded for a clean
  # printable string).
  local pw
  pw=$(head -c 32 /dev/urandom | base64 | tr -d '=+/' | head -c 32)
  if [ -z "$pw" ]; then
    echo "ERROR: failed to generate random password." >&2
    exit 1
  fi

  echo "Enter your S3 access key id and secret. These will be sealed"
  echo "alongside the kopia password into the SealedSecret manifest."
  printf "  S3 access key id: "
  local s3_access
  read -r s3_access
  printf "  S3 secret access key: "
  local s3_secret
  read -rs s3_secret
  echo ""
  if [ -z "$s3_access" ] || [ -z "$s3_secret" ]; then
    echo "ERROR: both S3 keys are required." >&2
    exit 1
  fi

  local tmp
  tmp=$(mktemp)
  trap 'rm -f "$tmp"' EXIT

  cat > "$tmp" <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: rustfs
  namespace: volsync-system
  labels:
    app.kubernetes.io/name: pvc-plumber
type: Opaque
stringData:
  kopia_password: "$pw"
  k8s-admin-access-key: "$s3_access"
  k8s-admin-secret-key: "$s3_secret"
EOF

  seal "$tmp" "$target"
  echo "Wrote sealed manifest: $target"
  echo ""
  echo "The plaintext kopia password is NOT printed here — it lives only"
  echo "in the cluster (sealed-secrets unwraps it at apply time) and in"
  echo "this generated SealedSecret. Lose the cluster + this file ="
  echo "lose access to existing kopia snapshots."
  echo ""
  echo "Next: git add $target && git commit && git push"
}

# ─────────────────────────────────────────────────────────────────────
# Argument parsing
# ─────────────────────────────────────────────────────────────────────
INPUT=""
OUTPUT=""
KOPIA_MODE="false"

while [ $# -gt 0 ]; do
  case "$1" in
    --in)               INPUT="$2"; shift 2 ;;
    --out)              OUTPUT="$2"; shift 2 ;;
    --kopia-password)   KOPIA_MODE="true"; shift ;;
    -h|--help)          usage; exit 0 ;;
    *)
      echo "ERROR: unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
done

preflight

if [ "$KOPIA_MODE" = "true" ]; then
  kopia_password_workflow
  exit 0
fi

# Read from stdin if no --in.
if [ -z "$INPUT" ]; then
  if [ -t 0 ]; then
    echo "ERROR: no input. Pipe a Secret manifest in or use --in <file>." >&2
    exit 2
  fi
  INPUT=$(mktemp)
  trap 'rm -f "$INPUT"' EXIT
  cat > "$INPUT"
fi

validate_secret_only "$INPUT"

# Write to stdout if no --out.
if [ -z "$OUTPUT" ]; then
  OUTPUT=/dev/stdout
fi

seal "$INPUT" "$OUTPUT"
